### ISSUE TITLE
Add support for the "did:indy" identifiers in published and shared AnonCred objects

### ISSUE THREAD

**Issue by swcurran** [hyperledger/indy-shared-rs#14]
Please update the implementation of CredX to add support for identifiers in objects either published on ledgers (DIDs, SCHEMA, CRED_DEF, REV_REG and REV_REG_ENTRY), or shared between participants (OFFER_CREDENTIAL, REQUEST_CREDENTIAL, ISSUE_CREDENTIAL, REQUEST_PROOF and PROOF).

As part of that -- please discuss what that will take.  My thought is that it should be relatively easy for the identifiers to be processed -- e.g. recognize which format is being used and process it accordingly. More challenging (I think) is that the identifiers could now contain extra information -- what ledger is to be used. How does that extra information get shared back to the entity that needs it?  For example,

* If the an old format ID is used, we don't know what ledger the referenced object is on. Do we use existing multi-ledger code for that?
* If a new format ID is used, we know exactly the ledger. How does that get used?  Is that needed/used by CredX?

I suspect that what we need to do is update the [Aries RFC 0592 Indy Attachments](https://github.com/hyperledger/aries-rfcs/tree/main/features/0592-indy-attachments) to add the format of the new identifiers and where they might be used.

FYI the formats being added are:

1. Extending where ever a DID is referenced in the existing identifiers with the `did:indy:<namespace>:` prefix.
2. Use the DID path format, such as for a [SCHEMA](https://hyperledger.github.io/indy-did-method/#schema), the URL is: [`did:indy:sovrin:F72i3Y3Q4i466efjYJYCHM/anoncreds/v0/SCHEMA/npdb/4.3.4`](https://indyscan.io/tx/SOVRIN_MAINNET/domain/56495)

**Comment by TimoGlastra** [comment]
We should probably take into account the usage of AnonCreds outside of the indy ecosystem when making this change. Not sure what role the validation of the identifiers play in this library, but ideally we remove the validation of the identifiers (or validate it's a legacy indy id or any uri according to the anoncreds wg spec). 

Then this library could be used as a generic anoncreds library, and it doesn't have to know about ledgers/indy at all. Maybe the repo could even be renamed to anoncreds something (or moved to the AnonCreds wg repo). And instead of updating RFC 0592 I think we should create a new format RFC for the anondreds format and removes all references to indy.

I think we should make the switch to generic AnonCreds at the same time as the switch to did:indy identifiers for indy as they're basically the same problem to solve

**Comment by swcurran** [comment]
Totally agree, @TimoGlastra.

In reviewing the AnonCreds spec and the existing objects, a potential issue is the in the CredDef object, the "ref" item is an integer, because in Indy that is the SeqNo of the Schema transaction.  Properly, it's value should be the "schemaId", a string and support all forms of SchemaId.  @andrewwhitehead (or anyone else) -- it would be good to know if/how changing the semantic meaning of "ref" will impact things.  Is there a way to do that with minimal impact in the CredX implementation?

**Comment by andrewwhitehead** [comment]
This will be addressed in https://github.com/hyperledger/anoncreds-rs
